### ISSUE TITLE
java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

### ISSUE THREAD

**Issue by lovachen** [Edward608/system_setting#10]
java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

D:\xx\build\system_setting\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
D:\xx\build\system_setting\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.

**Comment by paul678** [comment]
Probably caused by the library having an older compileSdkVersion than the app.

**Comment by MaximRyabovol** [comment]
Go to flutter/.pub-cache/hosted/pub.dartlang.org/system_setting-0.1.3/android/build.gradle and change "compileSdkVersion 27" to |compileSdkVersion 28|
