### ISSUE TITLE
Plugin in ios problem

### ISSUE THREAD

**Issue by zzzloving** [Edward608/system_setting#3]
I am experiencing this problem when using the plugin,I did not find a solution. my xcode 10.2.1, pod 1.5.3   
![image](https://user-images.githubusercontent.com/31347659/56713166-91f9c800-6763-11e9-95d9-e4d9582237aa.png)
What is the reason for this? How can I solve this problem?

**Comment by Edward608** [comment]
Please update to 0.1.3 and see if the issue still occur

**Comment by gerry05** [comment]
this issue still occur in 0.1.3.
