### ISSUE TITLE
Problem in Android

### ISSUE THREAD

**Issue by dmvvilela** [Edward608/system_setting#4]
It won't compile:

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':system_setting' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by Edward608** [comment]
Please update to 0.1.3, which updated the Kotlin version to 1.3.31
